export const LOCAL_ID_SECRET_VERSION = '0';
export const CHARSET = 'abcdefghijklmnopqrstuvwxyz1234567890';
export const RC4_SECRET_VERSION_KEY = 'b1b1';
export const RC4_SECRET_VERSION = '1';
export const LOCAL_ID_KEY = 'a1';
export const MINI_BROSWER_INFO_KEY = 'b1';
export const WEB_ID_KEY = 'webId';
export const WEB_SESSION_KEY = 'web_session';

export const INIT_STORAGE_VALUES = [
  'I38rHdgsjopgIvesdVwgIC+oIELmBZ5e3VwXLgFTIxS3bqwErFeexd0ekncAzMFYnqthIhJeSBMDKutRI3KsYorWHPtGrbV0P9WfIi/eWc6eYqtyQApPI37ekmR1QL+5Ii6sdnoeSfqYHqwl2qt5BfqJIvFbNLQ+ZPw7Ixdsxuwr4qtkIkrwIi/skZc3ICLdI3Oe0utl2ADZsL5eDSJsSPwXIEvsiVtJOPw8BuwfPpdeTDWOIx4VIiu6ZPwbJqt0IxHyoMAeVutWIvvs6PtPIiMzIih2sf6sS7h5rUOsfut4sM5eWz4VLoJeSWuGIx/eDqtcIios0qtlbLijPdpsI3deiqt3pW7e1g+2IhQaIET2NgqDI3zJqZ88IizuBVwUIvGF4e6edb5ekVtCIxAsfe3s0duZIh5e3DhSPqwDIkOs3BJs6Sesiqw/rd/eDuwjICFGzAoe0qwlzn/sSuwbI34LI3pTouwwaPwyosVNJpJs0j0siqtsIkOeDU3s6MW6IkJsSL7sx9IuIkJe1qtdIkqlOqwPtqtMIxve6utYIkes1Vw6IEosfqtANqwysqwIIvrdIxuz89q02ZJe3qtFIhu4IiAedqwoeWccpUOsDskuIhRytPwwzqwAIkesWqtuqIAsVF6s1IbLIiD=',
  '1',
];
